apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
data:
  POSTGRES_USER: YWltYW4=
  POSTGRES_PASSWORD: YWJjMTIz
  POSTGRES_DB: cG9zdGdyZXM=
  ADMIN_PASSWORD: YWJjMTIz
# echo -n 'Hello, World!' | base64
# SGVsbG8sIFdvcmxkIQ==
# aiman, abc123, postgres
